### ISSUE TITLE
Line breaks in Twitter template break formatting

### ISSUE THREAD

**Issue by LemmaEOF** [a2aaron/Cohoard#42]
I'm currently working on making a post using Cohoard, and I've found that the Twitter template includes line breaks in between the `<span>` for the display name and the `<span>` for the handle that seemingly mess up Cohost's Markdown parsing. It renders fine in Cohoard, but bringing it over to Cohost breaks it for some reason:
![Capto_Capture 2022-10-28_04-28-37_PM](https://user-images.githubusercontent.com/6722691/198750242-5f545d63-8c1a-4e0f-a560-e6fc23f2df0f.png)
I'm afraid I can't really figure out more of what's causing this on my own, but removing the line breaks seems to fix it so that looks like the best option for the template.

**Comment by a2aaron** [comment]
Ah hm, I think this was working when I initially wrote it, but maybe Cohost changed how they parse Markdown. I've updated the Twitter template and I think it should work now? (If the template still seems broken, try refreshing with shift-R--sometimes the browser will cache the old version of template, and doing shift-R refreshes without cache)

**Comment by a2aaron** [comment]
I'm gonna close this issue as fixed--i think i was able to properly fix it--but feel free to reopen it if the bug isn't fixed though.

**Comment by LemmaEOF** [comment]
Oh right, I forgot to comment, yeah it's looking good!
