### ISSUE TITLE
Feature request: user reference styling

### ISSUE THREAD

**Issue by AurySystem** [a2aaron/Cohoard#43]
being able to reffer to other users inline with a simular replacement system to the markup system.
probably with @{USER_KEY}.{field} or some other character to identify it in a message or timestamp. which acts as a shorthand for styled span with the text of the field being insterted.

example use: adding timestamps/ day breaks to MPSA style chatlogs since those often have "{handle} [{shorthandle}] started pestering {handle} [{shorthandle}]"

which would probably look like this in practice
@-- @JADE.handle [@Jade.short_handle] started pestering @DAVE.handle [@DAVE.short_handle]

we were seperately going to make a feature request for adding timestamps to the mspa template but that would probably be reduntant as that would likely be the test case for this.

hard part really is exposing it to terra in a way that let's templates configure the way this system works.
maybe they're stored in Postblock as a struct which holds: user mentioned, field, and timestamp/message context or something, wdk?
also allows for adding mentions to the discord template.

**Comment by a2aaron** [comment]
hm, i like this--lemme see how hard it'd be to try and make this

**Comment by a2aaron** [comment]
hm, as i'm implementing this, i'm realizing that this might be somewhat involved to implement. i do want to have at-mentions and also the pestlog headers, but i'm gonna need to rework some of the cohoard-rs api. specifically: i need to make it so that timestamps aren't invisible to Tera templates. this is easy to do (i could instead pass a list of PostBlocks mixed with Timestamps), but i'd probably need to move the timestamp and headline-generation stuff into the template, which isn't actually that hard but does require me to go through the templates and fix them up.

i'll keep working on this tomorrow

**Comment by a2aaron** [comment]
Implemented! Doing this also let me add stuff for @ mentions in the discord template. Currently, the implementation is a little jank. `@JADE.handle` will expand to `<span class="at-macro at-macro-JADE at-macro-JADE-handle">gnosticGardener</span>` at render time, so the templates never actually see the `@JADE.handle` text, but overall I think this is a decent implementation. You can stylize how the at-macros look by stylizing one of the `at-macro` classes. Hopefully, this provides enough control over how the spans look?

I will note that I had to change around how the message passing works overall, which is a breaking change. You can see how it's changed via the [CHANGELOG](https://github.com/a2aaron/Cohoard/blob/gh-pages/CHANGELOG.md) (in short, both timestamps and regular posts are no longer batched into PostBlocks but are just a steady stream of individual timestamps and posts. For something like the Pesterlog template, this is a pretty easy change, and only really makes the Discord template more complex.)

Thank you for your feature request! I will now close this issue, but feel free to reopen it if there is more functionality you would like from the feature.
