### ISSUE TITLE
Feature: Give MSPA a toggle to start Pesterlog in closed state

### ISSUE THREAD

**Issue by pleonasticTautology** [a2aaron/Cohoard#46]
this would be useful 1) as another layer for content warnings and 2) for anyone wanting to use Cohost to host MSPFAs

— alphy

**Comment by a2aaron** [comment]
Done! I have added a checkbox that allows the pesterlog to start in a closed state. (feel free to reopen this issue if the checkbox isnt sufficent/doesnt work for any reason)
