### ISSUE TITLE
Feature Request: Toggle to mark user in Discord template as a bot

### ISSUE THREAD

**Issue by pleonasticTautology** [a2aaron/Cohoard#47]
this would allow for 1:1 transcriptions of pluralkit conversations. — dave

**Comment by a2aaron** [comment]
Implemented! Unfortunately, the checkmark that discord uses seems to be made using SVG and I don't think Cohost allows for inline SVG (although I might be wrong about this). However, you can use the unicode symbol for a checkmark (✓) and it will show up (it's not exactly the same but looks reasonably close).

Here's what the tag looks like in Cohoard with a comparison to real Discord below

Cohoard:
<img width="696" alt="a screenshot of how cohoard renders the bot tag" src="https://user-images.githubusercontent.com/15718048/205108029-7553f6cc-73cd-4c52-a631-719e392d4481.png">

Real Discord:
<img width="591" alt="a screenshot of how discord renders the real bot tag with a checkmark" src="https://user-images.githubusercontent.com/15718048/205104951-8728356d-e057-499d-8cb7-8a2556527ab7.png">

You can access the bot tag by adding `bot_tag` to the Config Table--the value entered for the field is what text will show up in the bot tag (example shown below)--hence you're not just limited to making the tag only say "BOT".

<img width="484" alt="image" src="https://user-images.githubusercontent.com/15718048/205108754-112bf449-14c9-4247-aef5-e67f0f946ccc.png">


Feel free to reopen this issue if you have any additional requests/bug reports/etc related to the bot tags!

**Comment by pleonasticTautology** [comment]
oh this is great! the way pluralkit works, it doesn't have the checkmark anyway (proxies use webhooks), so we honestly forgot about it lmao — alphy
