### ISSUE TITLE
Feature request: MSPA template supporting different name color from text color

### ISSUE THREAD

**Issue by pleonasticTautology** [a2aaron/Cohoard#48]
in _Godfeels_, June Eg8ert's headmates Dare and Risk have different text colors from their name colors. Dare's name color is #7882ff and Risk's is #3e9fd1, while Dare's text color is #0715cd and Risk's is #005682. is there a way to support that in Cohoard? — alphy

**Comment by a2aaron** [comment]
Sure!

I've added a key to the Config table called `handle_color`. When provided, it will colorize the handle seperately from the body text.

(I probably won't be able to support all of the text shenanigans that Godfeels does--but simple ones like these are doable)

<img width="716" alt="image" src="https://user-images.githubusercontent.com/15718048/205193565-285ddbb8-f46d-4f1c-b585-76c29148330c.png">

**Comment by pleonasticTautology** [comment]
thanks! — alphy
